# GoCardless settings

GoCardless.environment = :sandbox

app_id: "PYV51QE9P6GM10NGFXP804BGH0AZKJ3PFQ5W81BX63W4RF08HJEMYJTA6SGY8EJC"
app_secret: "PS99PYHHV0RZR9TDG9EN7182H1MSPK80XHGCQ721CMPEWTKRVRPYXG3GKN689ZFA"
token: "V1S9A0B8Y48K0NZX22YQXQ2J1DPE058B0M38XFDBF8TV07FRNE4566FF18AM53KF"
merchant_id: "08RXPBQZE4"
